export {default as HomePage} from './HomePage'
export {default as CategoryPage} from './CategoryPage'
export {default as ExpressionPage} from './ExpressionPage'
export {default as InfoPage} from './InfoPage'
export {default as LandPage} from './LandPage'
export {default as SettingPage} from './SettingPage'